name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:

    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"

      - name: Run Android Lint
        run: ./gradlew lintDebug

      - name: Run Unit Test
        run: ./gradlew testDebug

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload apk file
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
